name             'php53'
maintainer       'Hisashi KOMINE'
maintainer_email 'hssh@hssh.jp'
license          'mit'
description      'Installs/Configures php53'
long_description 'Installs/Configures php53'
version          '0.1.0'
supports         'centos', '6.5'
